#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for pgrac cluster regression tests (placeholder, stage 0.4)
#
# IDENTIFICATION
#    src/test/cluster_regress/Makefile
#
# Author: SqlRush <sqlrush@gmail.com>
#
# Portions Copyright (c) 1996-2024, PostgreSQL Global Development Group
# Portions Copyright (c) 1994, Regents of the University of California
# Portions Copyright (c) 2026, pgrac contributors
#
# NOTES
#    This is a pgrac-original Makefile.  Stage 0.4 only sets up the
#    directory skeleton; actual regression tests will be filled in by
#    later feature points (Stage 1+ as cluster subsystems land).
#    See README.md in this directory.
#
#-------------------------------------------------------------------------

subdir = src/test/cluster_regress
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global


# ----------
# All standard targets are no-ops in stage 0.4 (placeholder).
# Real regression tests will land in later feature points.
# ----------
all check clean distclean maintainer-clean install installdirs \
uninstall installcheck:
	@echo "# cluster_regress: placeholder (no tests yet, see README.md)"

.PHONY: all check clean distclean maintainer-clean install installdirs \
        uninstall installcheck
