#-------------------------------------------------------------------------
#
# 013_conf.pl
#    End-to-end regression for the cluster topology configuration
#    framework introduced in stage 0.19.
#
#    Stage 0.19 ships the pgrac.conf parser, ClusterConfShmem, the
#    cluster.config_file GUC, and the pg_cluster_nodes view backed by
#    the cluster_get_nodes SRF (OID 8900).  This test runs against a
#    real PG instance and verifies:
#
#      - cluster.config_file GUC default and metadata.
#      - PGC_POSTMASTER context (runtime SET rejected).
#      - Single-node degraded fallback when pgrac.conf is absent
#        (postmaster starts; pg_cluster_nodes returns 1 row marked
#        is_self).
#      - pg_cluster_nodes column shape locked to seven columns
#        (node_id int, hostname text, interconnect_addr text,
#        public_addr text, role text, region text, is_self bool).
#      - Multi-node pgrac.conf is parsed and reflected in the view.
#      - cluster.node_id / pgrac.conf disagreement is rejected at
#        startup with a precise errhint.
#      - Duplicate [node.N] sections are rejected at startup.
#      - Malformed pgrac.conf produces a startup error with the line
#        number.
#      - Baseline regression: pg_stat_cluster_wait_events,
#        pg_stat_gcluster_wait_events, cluster.interconnect_tier
#        unaffected by the conf framework addition.
#
# IDENTIFICATION
#    src/test/cluster_tap/t/013_conf.pl
#
# Author: SqlRush <sqlrush@gmail.com>
#
# Portions Copyright (c) 2026, pgrac contributors
#
#-------------------------------------------------------------------------

use strict;
use warnings;

use FindBin;
use lib "$FindBin::RealBin/../lib";

use PostgreSQL::Test::Cluster;
use PostgreSQL::Test::Utils;
use Test::More;
use PgracClusterNode;


my $node = PgracClusterNode->new('main');
$node->init;
$node->start;


# ----------
# GUC default and metadata.
# ----------
my $cfg = $node->safe_psql('postgres', q{SHOW "cluster.config_file"});
ok($cfg ne '',
	"cluster.config_file default is set (got \"$cfg\")");

my $meta = $node->safe_psql(
	'postgres',
	q{SELECT vartype, context FROM pg_settings WHERE name = 'cluster.config_file'});
is($meta, "string|postmaster",
	'cluster.config_file metadata: vartype=string, context=postmaster');


# ----------
# Runtime SET is rejected (PGC_POSTMASTER).
# ----------
my ($stdout, $stderr);
$node->psql('postgres',
	q{SET "cluster.config_file" = '/tmp/whatever'},
	stdout => \$stdout, stderr => \$stderr);
like($stderr, qr/cannot be changed without restarting the server/i,
	'SET cluster.config_file at runtime is rejected (PGC_POSTMASTER)');


# ----------
# Single-node fallback: pgrac.conf is absent at this point because we
# never created one in this PGDATA.  pg_cluster_nodes must return 1
# row for the local node (is_self = true).
# ----------
# Uses spec-0.22 assert_pg_cluster_nodes_count helper.
$node->assert_pg_cluster_nodes_count('1',
	'pg_cluster_nodes returns 1 row in single-node degraded mode');

is($node->safe_psql('postgres',
		'SELECT is_self FROM pg_cluster_nodes'),
	't',
	'the single row in pg_cluster_nodes is_self = true');


# ----------
# Column shape contract: 7 columns with the expected types.
# ----------
my $cols = $node->safe_psql(
	'postgres',
	q{SELECT string_agg(attname || ':' || format_type(atttypid, atttypmod), ',' ORDER BY attnum)
	    FROM pg_attribute
	   WHERE attrelid = 'pg_cluster_nodes'::regclass
	     AND attnum > 0
	     AND NOT attisdropped});
is($cols,
	'node_id:integer,hostname:text,interconnect_addr:text,public_addr:text,role:text,region:text,is_self:boolean',
	'pg_cluster_nodes column contract: 7 columns with the expected types and order');


# ----------
# Baseline regression: previous-stage views and GUCs unaffected.
# ----------
is($node->safe_psql('postgres',
		'SELECT count(*) FROM pg_stat_cluster_wait_events'),
	'91',
	'pg_stat_cluster_wait_events returns 91 rows after spec-2.39');

is($node->safe_psql('postgres',
		'SELECT count(*) FROM pg_stat_gcluster_wait_events'),
	'91',
	'pg_stat_gcluster_wait_events returns 91 rows after spec-2.39');

is($node->safe_psql('postgres', q{SHOW "cluster.interconnect_tier"}),
	'stub',
	'cluster.interconnect_tier still defaults to stub after conf framework added');


# ----------
# Multi-node pgrac.conf: write [node.0] and [node.1], set
# cluster.node_id = 0, restart, expect 2 rows in the view with the
# right is_self flags.
# ----------
$node->stop;

my $conf_path = $node->data_dir . '/pgrac.conf';
PostgreSQL::Test::Utils::append_to_file($conf_path, <<'EOC');
# generated by 013_conf.pl
[cluster]
name = pgrac-test-013

[node.0]
interconnect_addr = 10.0.0.10:6432
hostname = test-node-0
role = primary
region = us-east-1a

[node.1]
interconnect_addr = 10.0.0.11:6432
hostname = test-node-1
role = standby
EOC

$node->append_conf('postgresql.conf', "cluster.node_id = 0\n");
$node->append_conf('postgresql.conf', "cluster.interconnect_tier = 'mock'\n");
# This test validates pgrac.conf parsing only.  Keep the cluster process
# stack enabled, but disable PCM/GCS so ordinary catalog reads do not wait
# for mock-tier block replies.
$node->append_conf('postgresql.conf', "cluster.pcm_grd_max_entries = 0\n");
$node->start;

is($node->safe_psql('postgres', 'SELECT count(*) FROM pg_cluster_nodes'),
	'2',
	'pg_cluster_nodes returns 2 rows after writing 2-node pgrac.conf');

is($node->safe_psql('postgres',
		'SELECT count(*) FROM pg_cluster_nodes WHERE is_self'),
	'1',
	'exactly one row in pg_cluster_nodes is_self = true');

is($node->safe_psql('postgres',
		q{SELECT node_id || '|' || role || '|' || hostname
		    FROM pg_cluster_nodes
		   WHERE is_self}),
	'0|primary|test-node-0',
	'self row matches [node.0] from pgrac.conf');

is($node->safe_psql('postgres',
		q{SELECT count(*) FROM pg_cluster_nodes
		   WHERE node_id = 1 AND role = 'standby'}),
	'1',
	'non-self row matches [node.1] from pgrac.conf');


# ----------
# cluster.node_id ↔ pgrac.conf disagreement: change cluster.node_id
# to 99 (not declared in pgrac.conf) and verify startup fails with
# the expected errhint.
# ----------
$node->stop;
$node->adjust_conf('postgresql.conf', 'cluster.node_id', '99');
unlink $node->logfile;
my $start_failed = !$node->start(fail_ok => 1);
ok($start_failed,
	'server refuses to start when cluster.node_id is not declared in pgrac.conf');

my $log = PostgreSQL::Test::Utils::slurp_file($node->logfile);
like($log, qr/cluster\.node_id=99 is not declared/,
	'startup failure log mentions the offending node id');
like($log, qr/Add a \[node\.99\] section/,
	'startup failure errhint suggests editing pgrac.conf');


# ----------
# Duplicate [node.0] section: clobber pgrac.conf with a duplicate and
# verify FATAL.
# ----------
unlink $conf_path;
PostgreSQL::Test::Utils::append_to_file($conf_path, <<'EOC');
[node.0]
interconnect_addr = 10.0.0.10:6432

[node.0]
interconnect_addr = 10.0.0.11:6432
EOC

$node->adjust_conf('postgresql.conf', 'cluster.node_id', '0');
unlink $node->logfile;
$start_failed = !$node->start(fail_ok => 1);
ok($start_failed,
	'server refuses to start when pgrac.conf has a duplicate [node.N] section');

$log = PostgreSQL::Test::Utils::slurp_file($node->logfile);
like($log, qr/duplicate \[node\.0\] section/,
	'startup failure log mentions duplicate section');


# ----------
# Malformed pgrac.conf: a key=value outside any section -> FATAL with
# line number.
# ----------
unlink $conf_path;
PostgreSQL::Test::Utils::append_to_file($conf_path, <<'EOC');
# pgrac.conf
stray_key = stray_value

[node.0]
interconnect_addr = 10.0.0.10:6432
EOC

unlink $node->logfile;
$start_failed = !$node->start(fail_ok => 1);
ok($start_failed,
	'server refuses to start with malformed pgrac.conf');

$log = PostgreSQL::Test::Utils::slurp_file($node->logfile);
like($log, qr/at line \d+ of/,
	'startup failure log includes line number context');


# ----------
# Recovery: remove pgrac.conf, restore cluster.node_id default, server
# should come back up on the single-node fallback path.
# ----------
unlink $conf_path;
$node->adjust_conf('postgresql.conf', 'cluster.node_id', '-1');
$node->start;
is($node->safe_psql('postgres', 'SELECT count(*) FROM pg_cluster_nodes'),
	'1',
	'server recovers after restoring single-node fallback');


$node->stop;

done_testing();
